<?php
session_start();
unset($_SESSION['login']);
unset($_SESSION['user_id']);
unset($_SESSION['real_name']);
unset($_SESSION['level']);
unset($_SESSION['expired_date']);
header('location:../login.php');
?>
